name: Deploy to Staging

on:
  push:
    branches:
      - main # Replace with your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.DUBKII_SSH_PRIVATE_KEY }}

      - name: Add Host Key
        run: |
          mkdir -p ~/.ssh
          if ! ssh-keygen -F "[145.223.77.182]:65002" > /dev/null; then
            ssh-keyscan -p 65002 145.223.77.182 >> ~/.ssh/known_hosts
          fi
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Staging
        run: |
          rsync -avz --exclude '.git' --exclude 'node_modules' --exclude '*.log' \
          -e "ssh -p 65002" ./ u405203284@145.223.77.182:/home/u405203284/domains/dubkii.com/public_html/staging/wp-content/plugins/dubkii-booking
